version: '3.8'
services:
  slack-git-compare:
    # image: docker.io/mvisonneau/slack-git-compare:latest
    # You can comment out the image name and use the following statement
    # to build the image against the current version of the repository
    build: ../..
    ports:
      - 8080:8080
    environment:
      SGC_CONFIG: /etc/config.yml
    volumes:
      - type: bind
        source: ./config.yml
        target: /etc/config.yml

networks:
  default:
    driver: bridge
